---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: reverse-words-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/gajananan/reverse-words
  - name: revision
    value: main
  - name: sslVerify
    value: "false"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: reverse-words-image
spec:
  type: image
  params:
  - name: url
    value: quay.io/gajananan/tekton-reversewords
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: reverse-words-build-pipeline
spec:
  resources:
  - name: cicd-git
    type: git
  - name: app-git
    type: git
  - name: app-image
    type: image
  params:
  - name: imageTag
    type: string
    default: latest
    description: Tag for the built image
  - name: signer-email
    type: string
    description: email of the artifact-signer
  - name: cicd-git-url
    type: string
    description:   git repo url "e.g. github.com/gajananan/reverse-words-cicd.git"
  - name: cicd-git-user-email
    type: string
  - name: cicd-git-user-name
    type: string
  tasks:

  - name: lint
    taskRef:
      name: golangci-lint
    params:
      - name: package
        value: github.com/gajananan/reverse-words
      - name: flags
        value: --verbose
      - name: GOOS
        value: "linux"
    resources:
      inputs:
      - name: source
        resource: app-git

  - name: test
    taskRef:
      name: golang-test
    runAfter:
      - lint
    params:
      - name: package
        value: github.com/gajananan/reverse-words
      - name: GOOS
        value: "linux"
    resources:
      inputs:
      - name: source
        resource: app-git

  - name: build-and-push
    taskRef:
      name: build-from-dockerfile
    runAfter:
      - test
    params:
      - name: DOCKERFILE_PATH
        value: "./Dockerfile"
      - name: IMAGE_TAG
        value: "$(params.imageTag)"
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image

  - name: update-stage-deployment-image
    taskRef:
      name: image-updater
    runAfter:
      - build-and-push
    params:
      - name: driver
        value: "github"
      - name: file-path
        value: "deployment.yaml"
      - name: image-repo
        value: "quay.io/gajananan/tekton-reversewords"
      - name: new-image-url
        value: "quay.io/gajananan/tekton-reversewords:$(params.imageTag)"
      - name: source-branch
        value: "stage"
      - name: source-repo
        value: "gajananan/reverse-words-cicd"
      - name: update-key
        value: "spec.template.spec.containers.0.image"
      - name: insecure
        value: "true"
      - name: branch-generate-name
        value: ""
  - name: ie-artifact-signing-task
    taskRef:
      name: ie-artifact-signing-task
    params:
      - name: source-branch
        value: "stage"
      - name: dest-branch
        value: "stage-plus"    
      - name: signer-email
        value: $(params.signer-email)
      - name: git-repo-url 
        value: $(params.cicd-git-url)
      - name: git-repo-user-email
        value: $(params.cicd-git-user-email)
      - name: git-repo-user-name
        value: $(params.cicd-git-user-name)
      - name: ignore-attrs
        value: "false"
    runAfter:
      - update-stage-deployment-image
    resources:
      inputs:
      - name: cicd 
        resource: cicd-git
