apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: reverse-words
  name: reverse-words
spec:
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: us.icr.io/mutation-advisor/tekton-reversewords:886128806b56918bd7bb431d1866b1ad9a72dbbb
        name: reverse-words
      imagePullSecrets:
      - name: mappregkey
