apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:6ce815b4aed83d3b270deacc8e87383ec34b56d8
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
