apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:d42f2dfe4102a54370cecee8a7e19b7185849d48
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
