apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: reverse-words
  name: reverse-words
spec:
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:5e22abf37b5dd8d8072ccf8cadd2a8a3ca297c0d
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
