apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:b9a1fbf5c727446bd1c48030e3f426bbe2021916
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
