apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:31bad394fb60b0ef9525eb58a1e020825fad9c0c
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
