apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:37b47f8ee5789b8eae72d90a207e7b2f7bdeff37
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
