apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:862bb54b2ac7d22cc1e9ca6a04d0c04450db382e
        name: reverse-words
