apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:21583939679e7b43a589d2d5ceb679f9d69576e1
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
