apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: reverse-words
  name: reverse-words
spec:
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:71749ecec30d3e6c62a437adc5d46eb94a27ec4d
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
