apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:61f586af6045507b06e782e3f4c49701622897a8
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
