apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:d5b7cafe81e1e72762447505c0fc941388d38f4c
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
