apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:4a742da069a9967644f3fc06bfb6a371553f69cb
        name: reverse-words
      imagePullSecrets:
        - name: registry-secret
