apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:ae3dd20426fa58996c11dcc398ef9d5cf9a50b42
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
