apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:5bc4fb5c38d444a306f8f88f578f640847b79ec0
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
