apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:5173ee168fb5fae763ac5c0647c7055aea72d0aa
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
