apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:9a1559b9f43a0cfd3711bcc459237b2a4deb8328
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
