apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:188e5e73dce3ff6fef5296b3e94043425d255fc3
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
