apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:6dc269ba4fd7fbd2fedc1a674216d9ccf8854770
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
