apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:110ce6921267d7fb9051094d46b6dffcccee8e8f
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
