apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/gajananan/tekton-reversewords:065dab5fe778eba90ec885f17db9c5af8cdccb9c
        name: reverse-words
      imagePullSecrets:
      - name: registry-secret
