apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-triggerbinding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: cicd-git-url
      value: https://github.com/gajananan/reverse-words-cicd
    - name: cicd-git-user-email
      value: gajan@jp.ibm.com
    - name: cicd-git-user-name
      value: gajan@jp.ibm.com
    - name: signer-email
      value: signer@enterprise.com
    - name: signer-pubkey-secret
      value: signer-pubkey
    - name: image-registry
      value: us.icr.io/mutation-advisor/*     
