apiVersion: v1
kind: ServiceAccount
metadata:
  name: ie-pipeline
secrets:
  - name: quay-user-pass
  - name: pipeline-keyring-secret
  - name: image-updater-secret
imagePullSecrets:
  - name: registry-secret
