apiVersion: research.ibm.com/v1alpha1
kind: ResourceProtectionProfile
metadata:
  name: rpp-merged
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  rules:
    - match:
        - kind: Service
        - kind: Deployment
        - kind: SealedSecret
        - kind: Ingress
  unprotectAttrs:
    - attrs:
        - metadata.annotations.argocd.argoproj.io/sync-wave
        - metadata.labels.app
        - metadata.labels.app.kubernetes.io/instance
      match:
        kind: ResourceProtectionProfile
        name: rpp-merged
    - attrs:
        - metadata.labels.app.kubernetes.io/instance
      match:
        kind: Deployment
        name: reverse-words
    - attrs:
        - metadata.labels.app.kubernetes.io/instance
      match:
        kind: SealedSecret
        name: registry-secret
    - attrs:
        - metadata.labels.app.kubernetes.io/instance
      match:
        kind: Ingress
        name: reverse-words
