apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-secret
  namespace: reversewords-ci
spec:
  encryptedData:
    .dockerconfigjson: AgBmGtaCNDzqO/o5kvyR6IuCLpMXv9L63zZrV1dAJOJxyvU7AD14dfVN9UscUAafZ4/bHudXake/4rOm+YaJ6xteywCWD6JXzUk7fBRjtvTZ57o71RDSNfA0nagZCtRhN/qJw64/MDSZHX3NW4VkkgXgKiQ88OlMrsajYG5jn2KqfxVw4hz/KAo7R1uuX1dKXASXVsNhbFbL4IoWBkb/MD5D1f91dRvg8a9+UkkmZkygKj7sERMnyA6dsll9yOGLLYhsvK1D+jsgt/Tv6GSx8pLewGtD+j8E2itnSp4Olg0WfTCNo56HVf+qy2lQ7Dxr5qVNoLgeKTScLTJekQKfJ+SvuQIh3+rl9N4nPEBXYGN9Xm6jmki6iGM/3nxK70dHVNRTnU33kQ/d9KM3g1uPjYQA4lP4kxtcx8fP7LjzB1mddUTV1sTKT+fq1ALgtyxir2r35s2xs3N+TbUMimNFHvSOkrJ9rLq8jSier4plJ5rUjHy1InuOKsf2jF7caAKZSDAd2Iz1MVHoe9JxtCPttbYauwV2LwRYIKTByxpJkPXPwRxKTu9pUy1/kqNcOp5IZCDLghvAffne7/85s+/Y1HPe1b1Dr/Z4SeYCXRod95Igz8dIUsk6jGB1Zee7xxj8JwMDGyg+XiyhMSZwE3lTxEc5Y9YfXNpQZoSzmow2dzSN61fnfmFcyHTUHiHsPVwVL7Dg6VsAHyGsOYdrk1fv17RMfQNhutb37+teiIQzFtvjSltpZioaqpkSdOyHe5L20vjyCmfnSEP0KgeFtfctcEVGkKQ43o8KYir96X+NBCmc7JoQ6zEM6mTvDWhmBxoLqGsBT3WFQ+eGa7kiY2cs0uPvwryhaLBBU5H+qNsekxpMGKRV1J1vv8ubYKOvHu0w5XjySLiiZTrQ2Whlje4J7oCqeZxs50eX52VKR6J75aohlGV9LyPjq0w+ySz3kc5FtYg8HF6ncYNnunZXXOy9Gt3EmuefPb7zoA==
  template:
    metadata:
      creationTimestamp: null
      name: registry-secret
      namespace: reversewords-ci
    type: kubernetes.io/dockerconfigjson

