apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: reverseword-build-triggertemplate
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
    - name: cicd-git-url
      description: The cicd git repository url 
    - name: ie-rsc-git-url
      description: The ie rsc git repository url
    - name: signer-email
      description: email of the artifacts signer
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: reversewords-git-$(uid)
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
        - name: sslVerify
          value: "false"
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: reverse-words-cicd-git-$(uid)
      spec:
        type: git
        params:
        - name: url
          value: $(params.cicd-git-url)
        - name: revision
          value: stage
        - name: sslVerify
          value: "false"
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: integrity-enforcer-resources-git-$(uid)
      spec:
        type: git
        params:
        - name: url
          value: $(params.ie-rsc-git-url)
        - name: revision
          value: master
        - name: sslVerify
          value: "false"
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: reversewords-build-pipeline-run-$(uid)
      spec:
        pipelineRef:
          name: reverse-words-build-pipeline
        serviceAccountNames:
          - taskName: build-and-push
            serviceAccountName: reversewords-pipeline
          - taskName: ie-artifact-signing-task
            serviceAccountName: reversewords-pipeline
        params:
          - name: imageTag
            value: $(params.gitrevision)
          - name: signer-email
            value: $(params.signer-email)
        resources:
          - name: app-git
            resourceRef:
              name: reversewords-git-$(uid)
          - name: cicd-git
            resourceRef:
              name: reverse-words-cicd-git-$(uid)
          - name: ie-rsc-git
            resourceRef:
              name: integrity-enforcer-resources-git-$(uid)
          - name: app-image
            resourceRef:
              name: reverse-words-image
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: reversewords-webhook
spec:
  serviceAccountName: reversewords-pipeline
  triggers:
    - name: git-reversewords-trigger
      interceptors:
        - github:
            secretRef:
              secretName: webhook-secret
              secretKey: secret
            eventTypes:
              - push
      bindings:
        - name: github-triggerbinding
      template:
        name: reverseword-build-triggertemplate
